model:
  test_size: 0.2
  random_state: 9
  balance_class_type: "smote"
  target: "Class"
  drop_features: ["credit_card_number", "timestamp", "merchant", "latitude", "longitude"]

data:
  raw_data: "data/raw/"
  process_data: "data/processed"